stages:
  collect_data:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - data/raw/iris_dataset.csv

  preprocess_data:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    - data/raw/iris_dataset.csv
    outs:
    - data/processed/X_train.npy
    - data/processed/X_test.npy
    - data/processed/y_train.npy
    - data/processed/y_test.npy
    - data/processed/scaler.joblib

  train_model:
    cmd: python src/train_model.py
    deps:
    - src/train_model.py
    - data/processed/X_train.npy
    - data/processed/y_train.npy
    - data/processed/scaler.joblib 
    outs:
    - models/rf_model.joblib

  test_model:
    cmd: python src/test_model.py
    deps:
    - src/test_model.py
    - models/rf_model.joblib
    - data/processed/X_test.npy
    - data/processed/y_test.npy
    - data/processed/scaler.joblib 

metrics:
- dvclive/metrics.json

plots:
- dvclive/plots/metrics:
    x: step 